name: gcdf1
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.8, <3.9
  - pip
  # BASICS
  # VISUALIZATION
  - matplotlib
  - seaborn
  # OTHER TOOLS
  - pip:
     - -e .  # install git checkout of sgd-utils in editable mode
     # add here only pip-packages that are not available in conda/conda-forge!
     # or use if your preferred way of installing packages is pip in a conda env :)
